docker:
  docker_config_json: ***REMOVED***
  registry_prefix: 
  image_name: ap-editor
  image_tag: jla-test

storage:
  storageClassName: standard

network:
  host: 192.168.49.2.nip.io

nodeSelector: {}
