apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files
  namespace: ap-editor
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi