apiVersion: v1
kind: Service
metadata:
  name: ap-editor-webapp
  namespace: ap-editor
  labels:
    app: ap-editor-webapp
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ap-editor-webapp